version: "3.9"
services:
  backend:
    build: ./backend
    container_name: farm93-backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: farm93-frontend
    restart: always
    ports:
      - "80:80"
